import { profileConfig } from "../profile.config.ts";

type GitHubUser = {
  followers: number;
  public_repos: number;
};

type GitHubRepo = {
  name: string;
  html_url: string;
  description: string | null;
  homepage: string | null;
  fork: boolean;
  archived: boolean;
  language: string | null;
  topics: string[];
  pushed_at: string;
};

type BadgeConfig = {
  label: string;
  message: string;
  color: string;
  logo?: string;
  link?: string;
  style?: string;
};

type ProjectOverride = {
  emoji?: string;
  description?: string;
};

const README_PATH = new URL("../README.md", import.meta.url);
const GENERATED_HEADER = "<!-- This file is generated by `bun run generate`. -->";
const WAKA_START = `<!--START_SECTION:${profileConfig.waka.sectionName}-->`;
const WAKA_END = `<!--END_SECTION:${profileConfig.waka.sectionName}-->`;
const DEFAULT_WAKA_PLACEHOLDER = [
  "```text",
  "WakaTime stats will appear here after the scheduled workflow runs.",
  "```",
].join("\n");
const projectOverrides: Record<string, ProjectOverride> = profileConfig.projectOverrides;

async function main() {
  const existingReadme = await readTextIfExists(README_PATH);
  const wakaSection =
    normalizeWakaContent(process.env.WAKA_SECTION_CONTENT) ??
    extractSection(existingReadme, WAKA_START, WAKA_END) ??
    DEFAULT_WAKA_PLACEHOLDER;

  const [user, repos] = await Promise.all([fetchUser(), fetchRepos()]);
  const recentProjects = selectRecentProjects(repos);
  const nextReadme = renderReadme(user, recentProjects, wakaSection);

  if (Bun.argv.includes("--check")) {
    if (existingReadme !== nextReadme) {
      console.error("README.md is out of date. Run `bun run generate`.");
      process.exit(1);
    }

    console.log("README.md is up to date.");
    return;
  }

  if (existingReadme === nextReadme) {
    console.log("README.md already up to date.");
    return;
  }

  await Bun.write(README_PATH, nextReadme);
  console.log(`README.md updated with ${recentProjects.length} recent projects.`);
}

async function readTextIfExists(path: URL) {
  const file = Bun.file(path);
  return (await file.exists()) ? file.text() : "";
}

function extractSection(content: string, startMarker: string, endMarker: string) {
  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
    return null;
  }

  const sectionStart = startIndex + startMarker.length;
  return content.slice(sectionStart, endIndex).trim() || DEFAULT_WAKA_PLACEHOLDER;
}

function normalizeWakaContent(content?: string) {
  if (!content) {
    return null;
  }

  const trimmed = content.trim();

  if (!trimmed) {
    return null;
  }

  return trimmed.replace(/^README stats current output:\s*/i, "").trim() || null;
}

async function fetchUser() {
  return githubRequest<GitHubUser>(`/users/${profileConfig.username}`);
}

async function fetchRepos() {
  const repos: GitHubRepo[] = [];

  for (let page = 1; ; page += 1) {
    const batch = await githubRequest<GitHubRepo[]>(
      `/users/${profileConfig.username}/repos?sort=updated&direction=desc&per_page=100&page=${page}`,
    );

    repos.push(...batch);

    if (batch.length < 100) {
      return repos;
    }
  }
}

async function githubRequest<T>(path: string): Promise<T> {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const response = await fetch(`https://api.github.com${path}`, {
    headers: {
      Accept: "application/vnd.github+json",
      "User-Agent": `${profileConfig.username}-github-profile-generator`,
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });

  if (!response.ok) {
    throw new Error(`GitHub API request failed: ${response.status} ${response.statusText}`);
  }

  return (await response.json()) as T;
}

function selectRecentProjects(repos: GitHubRepo[]) {
  const cutoff = new Date();
  cutoff.setMonth(cutoff.getMonth() - profileConfig.recentProjects.lookbackMonths);
  const excludedRepoNames = new Set(
    profileConfig.recentProjects.excludedRepoNames.map((repoName) => repoName.toLowerCase()),
  );

  return repos
    .filter((repo) => !excludedRepoNames.has(repo.name.toLowerCase()))
    .filter((repo) => !profileConfig.recentProjects.excludeForks || !repo.fork)
    .filter((repo) => !profileConfig.recentProjects.excludeArchived || !repo.archived)
    .filter((repo) => new Date(repo.pushed_at) >= cutoff)
    .sort((left, right) => Date.parse(right.pushed_at) - Date.parse(left.pushed_at))
    .slice(0, profileConfig.recentProjects.maxCount);
}

function renderReadme(user: GitHubUser, recentProjects: GitHubRepo[], wakaSection: string) {
  const statsTheme = encodeURIComponent(profileConfig.stats.theme);
  const skillIcons = profileConfig.skillIcons.join(",");
  const badges = profileConfig.badges.map(renderBadge).join("\n");
  const intro = profileConfig.intro.map((line) => `- ${line}`).join("\n");
  const quickFacts = profileConfig.quickFacts
    .map((fact) => `- ${fact.emoji} ${fact.label}: ${fact.value}`)
    .join("\n");
  const projects = recentProjects.length
    ? recentProjects.map(renderProject).join("\n")
    : "- Nothing public has been pushed in the last 6 months yet.";

  return `${GENERATED_HEADER}

# Hi, I'm ${profileConfig.name} 👋

${profileConfig.headline}

![Profile views](https://komarev.com/ghpvc/?username=${encodeURIComponent(profileConfig.username)}&label=Profile%20views&color=3b82f6&style=flat-square)
![Public repos](https://img.shields.io/badge/Public%20Repos-${user.public_repos}-111827?style=flat-square&logo=github)
![Followers](https://img.shields.io/badge/Followers-${user.followers}-2563eb?style=flat-square&logo=github)

${badges}

${intro}
${quickFacts}

## Stack

![Tech stack](https://skillicons.dev/icons?i=${encodeURIComponent(skillIcons)}&perline=6)

## GitHub stats

<table>
  <tr>
    <td>
      <img src="https://github-readme-stats.vercel.app/api?username=${encodeURIComponent(profileConfig.username)}&show_icons=true&theme=${statsTheme}&hide_border=true&rank_icon=github" alt="${profileConfig.name} GitHub stats" />
    </td>
    <td>
      <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=${encodeURIComponent(profileConfig.username)}&layout=compact&theme=${statsTheme}&hide_border=true&langs_count=8" alt="${profileConfig.name} top languages" />
    </td>
  </tr>
</table>

<img src="https://streak-stats.demolab.com?user=${encodeURIComponent(profileConfig.username)}&theme=${statsTheme}&hide_border=true" alt="${profileConfig.name} contribution streak" />

<img src="https://github-profile-trophy.vercel.app/?username=${encodeURIComponent(profileConfig.username)}&theme=algolia&no-frame=true&no-bg=true&margin-w=8&row=1" alt="${profileConfig.name} trophies" />

## Recently updated projects

${projects}

## ${profileConfig.waka.title}

${WAKA_START}
${wakaSection}
${WAKA_END}
`;
}

function renderBadge(badge: BadgeConfig) {
  const style = badge.style ?? "flat-square";
  const url = new URL(
    `https://img.shields.io/badge/${escapeBadgePart(badge.label)}-${escapeBadgePart(badge.message)}-${badge.color}`,
  );

  url.searchParams.set("style", style);

  if (badge.logo) {
    url.searchParams.set("logo", badge.logo);
  }

  const markdown = `![${badge.label} badge](${url.toString()})`;
  return badge.link ? `[${markdown}](${badge.link})` : markdown;
}

function escapeBadgePart(value: string) {
  return encodeURIComponent(value.replace(/-/g, "--").replace(/_/g, "__").replace(/ /g, "_"));
}

function renderProject(repo: GitHubRepo) {
  const metadata = [repo.language, relativeDate(new Date(repo.pushed_at))].filter(Boolean).join(" · ");
  const description = resolveDescription(repo);

  return `- ${resolveEmoji(repo)} [${repo.name}](${repo.html_url})${metadata ? ` · ${metadata}` : ""}. ${description}`;
}

function resolveDescription(repo: GitHubRepo) {
  const override = projectOverrides[repo.name]?.description;

  if (override) {
    return override;
  }

  if (repo.description) {
    return truncate(repo.description, profileConfig.recentProjects.descriptionMaxLength);
  }

  if (repo.topics.length > 0) {
    return `Recently updated work around ${repo.topics.slice(0, 3).join(", ")}.`;
  }

  if (repo.language) {
    return `Recently updated ${repo.language} project.`;
  }

  return "Recently updated public project.";
}

function resolveEmoji(repo: GitHubRepo) {
  const override = projectOverrides[repo.name]?.emoji;

  if (override) {
    return override;
  }

  const haystack = `${repo.name} ${repo.description ?? ""} ${repo.topics.join(" ")}`.toLowerCase();
  const rules: Array<[RegExp, string]> = [
    [/\b(agent|ai|llm|prompt)\b/, "🤖"],
    [/\b(cli|terminal|shell|command|tool|tooling)\b/, "🛠️"],
    [/\b(trace|observability|metric|metrics|stats|analytics|dashboard)\b/, "📊"],
    [/\b(api|server|backend|worker|queue)\b/, "⚙️"],
    [/\b(site|web|frontend|ui|landing|blog)\b/, "🖥️"],
    [/\b(package|library|sdk|module)\b/, "📦"],
    [/\b(config|dotfiles|setup|gitignore)\b/, "🧰"],
  ];

  for (const [pattern, emoji] of rules) {
    if (pattern.test(haystack)) {
      return emoji;
    }
  }

  const languageFallbacks: Record<string, string> = {
    Go: "🐹",
    TypeScript: "🔷",
    JavaScript: "⚡",
    PHP: "🐘",
    Rust: "🦀",
    Ruby: "💎",
    Python: "🐍",
  };

  return repo.language ? languageFallbacks[repo.language] ?? "✨" : "✨";
}

function truncate(value: string, maxLength: number) {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength - 1).trimEnd()}…`;
}

function relativeDate(date: Date) {
  const diffDays = Math.max(0, Math.floor((Date.now() - date.getTime()) / 86_400_000));

  if (diffDays === 0) {
    return "updated today";
  }

  if (diffDays === 1) {
    return "updated yesterday";
  }

  if (diffDays < 7) {
    return `updated ${diffDays}d ago`;
  }

  if (diffDays < 30) {
    return `updated ${Math.floor(diffDays / 7)}w ago`;
  }

  return `updated ${Math.floor(diffDays / 30)}mo ago`;
}

await main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
